# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import podcast.playlist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name=b'Omschrijving')),
                ('published', models.BooleanField(default=False, verbose_name=b'Gepubliceerd')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name=b'Slug')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name=b'Naam')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'Playlist',
                'verbose_name_plural': 'Playlists',
            },
        ),
        migrations.CreateModel(
            name='PlayListFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text=b'Toegestaan: .mp3, .wav', upload_to=podcast.playlist.models.playlist_file_upload_to, validators=[podcast.playlist.models.validate_file], verbose_name=b'Bestand')),
                ('publication_datetime', models.DateTimeField(verbose_name=b'Gepubliceerd op')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name=b'Slug')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name=b'Naam')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='playlist.PlayList', verbose_name=b'Playlist')),
            ],
            options={
                'ordering': ['playlist', 'publication_datetime'],
                'verbose_name': 'Audiobestand',
                'verbose_name_plural': 'Audiobestanden',
            },
        ),
    ]
