# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import podcast.playlist.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayListFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name=b'Samenvatting')),
                ('file', models.FileField(blank=True, help_text=b'Toegestaan: .mp3', upload_to=podcast.playlist.models.playlist_file_upload_to, validators=[podcast.playlist.models.validate_file], verbose_name=b'Bestand')),
                ('playlist', models.CharField(choices=[(b'geluidjes', b'Geluidjes')], max_length=20, verbose_name=b'Playlist')),
                ('publication_datetime', models.DateTimeField(verbose_name=b'Gepubliceerd op')),
                ('slug', models.SlugField(max_length=20, unique=True, verbose_name=b'Slug')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name=b'Naam')),
            ],
            options={
                'ordering': ['playlist', 'publication_datetime'],
                'verbose_name': 'Audiobestand',
                'verbose_name_plural': 'Audiobestanden',
            },
        ),
    ]
